name: 'cache yarn folder'
description: 'Will cache the folder'
inputs:
  folder:
    description: 'folder to cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: test interpolation
      run: |
        echo ${{ runner.os }}-yarn-${{ hashFiles(format('{0}/{1}', inputs.folder, 'unified.lcov')) }}
      shell: bash
