name: auto-tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: autocreatetag
        run:
          set -o xtrace
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git

          commit_msg=$(git log --format=%B -n 1 ${{ github.event.after }}|sed 's/ *//g')
          git checkout master
          git tag ${commit_msg} ${{ github.event.after }}
          git push origin ${commit_msg}
