name: on-create-sample

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: debug
        run:
          echo "current tag" ${{ github.ref }}
