on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test matcher
    steps:
      - name: test some commands
        run: |
          echo "::debug::Set the Octocat variable"
          echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v1

      - name: Check whether build can be skipped
        id: skip-check
        uses: taksan/commit-message-matcher@main
        with:
          pattern: "\\[skip-build\\]"


      - uses: ./.github/workflows/subaction
        with:
          folder: "path"
