name: Update pull-request to replace prNumber
on: [pull_request]

jobs:
  update_pr_description:
    runs-on: ubuntu-latest
    steps:
      - name: replace pr description
        uses: claudiamatosa/github-action-replace-pr-body@v1.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Ge PR number
        run: |
          #!/bin/bash
          env
          echo "${{ github.ref }}"
          echo ${{ github.payload.pull_request.head.ref }}
          echo ${{ github.context.payload.pull_request.number }}

          PR_NUMBER=$(echo "${{ github.ref }}" | cut -d/ -f3)
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
          ISSUE_NUMBER=$(echo ${{ github.payload.pull_request.head.ref }} | cut -f- -d2)
          echo "ISSUE_NUMBER=${ISSUE_NUMBER}" >> $GITHUB_ENV

      - name: prepare PR description
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: 'issue-\d+'
          body-template: |
            Merging into '%basebranch%'
            ![Coverage Badge](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/taksan/ebeaf38ec43a8e3c021a1c92126b49f9/raw/jira-worklog-grid__pull_${{ github.context.payload.pull_request.number }}.json)
          body-update-action: 'suffix'
          body-uppercase-base-match: false
