on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test matcher
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"


      - uses: taksan/compute-coverage-stats@v1
        id: compute-coverage-stats
        with:
          coverage-file: unified.lcov

      - run: echo ${{ steps.compute-coverage-stats.outputs.coverage }} ${{ steps.compute-coverage-stats.outputs.coverage-color }}
        shell: bash