on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test matcher
    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2
      - name: Check whether build can be skipped
        id: skip-check
        uses: taksan/commit-message-matcher@main
        with:
          pattern: "\\[skip-build\\]"


      - uses: ./.github/workflows/subaction
        with:
          folder: "path"
