on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test matcher
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: ./.github/worfklow/subaction
        with:
          pattern: "Seee me"