name: on-create-sample

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir foo
          echo ${{ github.ref }} >> foo/README.md

      - uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: "foo/*.md"

  release-notes:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v2
        with:
          name: release-artifact

      - name: create tag name
        run:
          RELEASE_TAG=$(echo ${{ github.ref }} | cut -d/ -f3)

          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

          ls -lR

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          artifacts: "*.md"
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release notes
        uses: lakto/gren-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          options: '--override'