name: on-create-sample

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ github.ref }} >> README.md
      - uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: "*.md"

  release-notes:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v2
        with:
          name: release-artifact

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          artifacts: "*.md"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release notes
        uses: lakto/gren-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          options: '--override --prerelease'