on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test matcher
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: taksan/commit-message-matcher@v1
        with:
          pattern: '\[skip-build\]|nothing'
      - run: echo ${{ steps.foo.outputs.matches }}
        shell: bash
      - id: foo2
        uses: taksan/commit-message-matcher@v1
        with:
          pattern: 'whatever'
      - run: echo ${{ steps.foo2.outputs.matches }}
        shell: bash