on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test matcher
    steps:
      - uses: actions/checkout@v2
      - name: Check whether build can be skipped
        id: skip-check
        uses: taksan/commit-message-matcher@v1
        with:
          pattern: "\\[skip-build\\]"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: ./.github/workflows/subaction
        with:
          folder: "path"
