name: on-create-sample

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world

      - name: debug
        run:
          echo ${{ github.ref }}
          echo ${{ github }}
